services:
  netty-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VERSION: "0.0.1-SNAPSHOT"
        IMPLEMENTATION: netty
        PORT: 50051
    image: helidon-vs-netty-benchmark:0.0.1-SNAPSHOT-netty
    ports:
      - "50051:50051"
    restart: unless-stopped

  helidon-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VERSION: "0.0.1-SNAPSHOT"
        IMPLEMENTATION: helidon
        PORT: 50052
    image: helidon-vs-netty-benchmark:0.0.1-SNAPSHOT-helidon
    ports:
      - "50052:50052"
    restart: unless-stopped
